services:
  selenium:
    # 通常の環境では、以下のイメージを使います。
    image: selenium/standalone-chrome
    ports:
      # Selenium サーバに接続するポート
      - "4444-4448:4444"
      # VNC で接続するポート
      - "5900-5904:5900"
      # Selenium サーバのログを出力するポート
      - "7900-7904:7900"
      # コンテナが使用するメモリの上限を設定
    shm_size: "2gb"

  db:
    build:
      context: .
      dockerfile: ./db/Dockerfile
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      TZ: 'Asia/Tokyo'
      POSTGRES_DB: 'keibaai'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'postgres'

  keiba-ai:
    build:
      context: .
      dockerfile: ./ai/Dockerfile
    volumes:
      - ./ai:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    user: 1000:1000
    tty: true

volumes:
  db-store:
