services:
  selenium:
    container_name: selenium-chrome
    # 通常の環境では、以下のイメージを使います。
    image: selenium/standalone-chrome
    ports:
      # Selenium サーバに接続するポート
      - "4444:4444"
      # VNC で接続するポート
      - "5900:5900"
      # Selenium サーバのログを出力するポート
      - "7900:7900"
      # コンテナが使用するメモリの上限を設定
    shm_size: "2gb"
  keiba-ai:
    build:
      context: .
      dockerfile: ./ai/Dockerfile
    volumes:
      - ./ai:/app
    user: 1000:1000
    tty: true
